name: Trigger auto deployment for test-fastapi-container-app1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ feat-101 ]
    paths:
    - '**'
    - '.github/workflows/test-fastapi-container-app1-AutoDeployTrigger-d61d07b7-5e81-4760-8bd2-0fb4f9ca33fa.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTFASTAPICONTAINERAPP1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTFASTAPICONTAINERAPP1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTFASTAPICONTAINERAPP1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: testregisterysllm.azurecr.io
          registryUsername: ${{ secrets.TESTFASTAPICONTAINERAPP1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTFASTAPICONTAINERAPP1_REGISTRY_PASSWORD }}
          containerAppName: test-fastapi-container-app1
          resourceGroup: test-app-ai
          imageToBuild: testregisterysllm.azurecr.io/test-fastapi-container-app1:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


